[package]
name = "linear_regression"
version = "0.1.0"
authors = ["LukeMathWalker"]
edition = "2018"
workspace = ".."

[dependencies]
ndarray = "0.15"
ndarray-linalg = { version = "0.14", features = ["openblas-system"] }
ndarray-stats = "0.5"
ndarray-rand = "0.14"
rand = "0.8"
